### PR TITLE
Update a post on micro frontend

### PR DESCRIPTION
**Pull request by thecoder8890**
I am making a series of tutorial on micro frontend this is one article of them.

### CODE REVIEW

**Comment by marconi1992** [comment]
Great Article.

Some feedback.

I like the part **"Because you can use different frameworks and technologies it does not mean that you have to."**, nevertheless, it still needs an explanation about when we have to. I recommend mentioning in the "When to Use Micro-Frontends" the following sentence related to tech agnostic:

- **To gradually migrate from an old framework to a new one.**

It's because we've seen a lot of companies who implemented this architecture before we labeled it as MFEs when **at some point in the migration they had two or more frameworks coexisting in the same application**.

**Comment by marconi1992** [comment]
Also, you mentioned about the **Build Time Integration** but not about the **Run Time Integration**. You could mention it as well.

Regarding **Sharing global state and communication between apps**. IMO the need for sharing a  global state or using complex communication mechanisms like RxJS is a sign that the Microfrontends boundaries are not well defined. It's pretty much the same that sharing a database between Microservices.

**Comment by marconi1992** [comment]
Idenpently of my comments this a really valuable article. Looking forward to reading the upcoming ones :smile:

**Comment by thecoder8890** [comment]
Thanks :)

**Pull request merged**
